### ISSUE TITLE
Missing geometry column and duplicates from deprecated osm versions

### ISSUE THREAD

**Issue by nanodan** [gcp-pdp/geo-openstreetmap#17]
In the previous tables available in BigQuery, there was a geometry column was present in these tables and we were able to just pull directly. We keep all the tables separate in our copy in BQ environment for efficient joins. It's useful to have the associated geography object for each osm-id as each should represent a unique discrete location(s) on the surface of the Earth and we can quickly do things like st_intersects and st_contains.. 

When we generate, I can just add an extra step that joins on the features/layers table to grab the geometry columns. 

However there are some inconsistencies in these tables that prevent me from efficiently recreating the associated geometry object for each way and node.

For example, osm_id = 9820303

This is a pretty old static osm id which represents a way in North Dakota. It hasn't changed in the last 7 years according to openstreetmap.org. The user id matches that shown in the planet_ways table. It's classed as a Highway: Service way. However, in the planet_layers table it shows up twice:

(1) as a building layer lines, with the linestring
(2) as a building layer polygon, with a multipolygon

It doesn't have an associated multipolygon in OSM and isn't a building. checking on a map, the linestring is correct, the multipolygon however is a building in Italy.

In the planet_features table, it shows version 3 with the correct linestring, version 1 with the building tags, though version 1 as a building doesn't show up in the history_ways table. 

In the planet_layers table, the osm_version is null, so it isn't clear that they come from different osm versions or which is the "winner" to pick; I also don't think deprecated OSM versions should be present in the "current" tables.

So to properly reconstruct each of the ways and nodes tables with their geometries we would have to join on the features table, and then find the most recent osm version id, and then pick that geometry as the winner (even though the deprecated osm version has a more recent timestamp somehow).

I may be misinterpreting something here so feel free to correct.

**Comment by pseveryn** [comment]
@nanodan , thank you very much for such detailed explanation!

What I see for now:
1. OpenStreetMap has 2 objects with `id=9820303`:

- way - road in North Dakota (version 3) (https://www.openstreetmap.org/way/9820303)
- relation - building in Italy (version 1) (https://www.openstreetmap.org/relation/9820303)

2. Both objects are correctly presented at the `palnet_features` table
`SELECT * FROM bigquery-public-data.geo_openstreetmap.planet_features WHERE osm_id='9820303'`

3. Each of the objects is correctly presented at the `planet_ways` and `planet_relations` tables:
`SELECT * FROM  bigquery-public-data.geo_openstreetmap.planet_ways  WHERE id=9820303`
`SELECT * FROM  bigquery-public-data.geo_openstreetmap.planet_relations WHERE id=9820303`

4. But in the `planet_layers` both of the objects have attributes of "relation - building in Italy (version 1)". This should be fixed.
`SELECT * FROM  bigquery-public-data.geo_openstreetmap.planet_layers  WHERE osm_id=9820303`

5. Also, I see that `history_ways` contains duplications of `version=2`. Need to check how it happened
`SELECT * FROM  bigquery-public-data.geo_openstreetmap.history_ways  WHERE id=9820303 AND version=2`

**Comment by nanodan** [comment]
@Pseverin you're right, I missed checking the relation in OSM. It seems the issue is present only in the planet_layers table and history_ways table.

Can we modify the process to not have the null geometry columns in the planet_ways and nodes tables? Or is the plan to keep those null and require a join on the planet_features table? Right now with the structure there is not an easy way to join and know which is the right feature to extract. If we look at the planet_ways table and the planet_features table for osm_id = 9820303 the only way to get the right geometry would be to match up the key-value pairs.

**Comment by pseveryn** [comment]
@nanodan, yes, we will add the geomentry data into the planet_nodes/ways/relations tables.
Also, we are already working on the planet_layers problem and history_ways duplication.

**Comment by pseveryn** [comment]
@nanodan , please check improved data in the `bigquery-public-data.geo_openstreetmap` dataset. All issues that were mentioned in this issue are fixed.

**Comment by nanodan** [comment]
@Pseverin The fix looks good, I'm not seeing any of the previous issues.

- Roads with missing geometry
-- returns 12,094 results; very few. However, spot checking these, they are generally parking lots, buildings, driveways that have been generated as polygons in OSM. Still not sure why the polygons  are not showing up in the geometry column, but they aren't road line-strings in any case.
```
CREATE TEMP FUNCTION f_Highway()
             RETURNS ARRAY<STRING>
                  AS (
                      ARRAY['motorway', 'trunk', 'primary'
                          , 'secondary', 'tertiary', 'unclassified'
                          , 'residential', 'motorway_link', 'trunk_link'
                          , 'primary_link', 'secondary_link', 'tertiary_link'
                          , 'service', 'road']
);

with t_test as ( 
    select *
         , countif(key = 'area' and value = 'yes') over(partition by id) as area_tag
         , countif(key = 'highway' and value in unnest(f_Highway())) over(partition by id) as highway_tag
      from `bigquery-public-data.geo_openstreetmap.planet_ways` t, t.all_tags ata
     where geometry is null
)
select *
  from t_test
 where highway_tag = 1
   and area_tag = 0
 ```
- Ways with duplicates in history
-- zero found: `select id, version, count(1) cnt from bigquery-public-data.geo_openstreetmap.history_ways group by 1, 2 having cnt > 1`

**Comment by pseveryn** [comment]
@nanodan thank you that noticed this problem. After fix in https://github.com/gcp-pdp/geo-openstreetmap/pull/25 there are only 743 results from the above query.

I've checked some of them and noticed that these OSM objects are present in `planet_ways`, but not present in `planet_features`. This means that they were failed to process with GDAL

**Comment by allenday** [comment]
can we further define the edge case here for the remaining 743 results and close this issue?

**Comment by pseveryn** [comment]
@allenday , most likely that these 743 objects contain some problems in `tags`, that why GDAL skips them during processing

**Comment by allenday** [comment]
I'm closing this. Problem appears to be data quality related and that logic here is correct.
